### ISSUE TITLE
OC: Failed to drop ACPI 54445353 34646866635F6878 0 (0) - Not Found

### ISSUE THREAD

**Issue by jackhanyuan** [Yetarian/Yetarian-XPS15-7590-i5-Hackintosh-Monterey12.5#1]
使用仓库OC升级12.5.1遇到了问题，进度条走一半后会重启，屏幕出现OC: Failed to drop ACPI 54445353 34646866635F6878 0 (0) Not Found，然后会自动进入Recovery。

**Comment by jackhanyuan** [comment]
已经找到问题，升级过程中不知道怎么系统文件损坏了，重新下的完整镜像覆盖升级了一遍就好了！！

**Comment by Yetarian** [comment]
Okok，我上次收到你的邮件，并且回复了，但是发送失败了我看了一下，这次做的oc我多次试验了应该来时没有任何问题，正常使用那些没有任何问题，wifi也能跑满至少是百兆的，下一次我准备做Ventura的适配，上次做失败了，如果我做好了，第一时间发布。Xps15的bios非常适合做黑苹果基本不需要改动，还是很完美的。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年9月2日 18:35
收件人: ***@***.***>
抄送: ***@***.***>
主题: Re: [Yetarian/Yetarian-XPS15-7590-i5-Hackintosh-Monterey12.5] OC: Failed to drop ACPI 54445353 34646866635F6878 0 (0) - Not Found (Issue #1)


已经找到问题，升级过程中不知道怎么系统文件损坏了，重新下的完整镜像覆盖升级了一遍就好了！！

―

**Comment by Yetarian** [comment]
有问题随时邮件联系我

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年9月2日 18:35
收件人: ***@***.***>
抄送: ***@***.***>
主题: Re: [Yetarian/Yetarian-XPS15-7590-i5-Hackintosh-Monterey12.5] OC: Failed to drop ACPI 54445353 34646866635F6878 0 (0) - Not Found (Issue #1)


已经找到问题，升级过程中不知道怎么系统文件损坏了，重新下的完整镜像覆盖升级了一遍就好了！！

―
